### ISSUE TITLE
Can't install with packer/vim-plug

### ISSUE THREAD

**Issue by ram02z** [AckslD/nvim-revJ.lua#14]
> Upon running `PackerSync`

![image](https://user-images.githubusercontent.com/59267627/120086320-3df60600-c0d6-11eb-8973-c71a2628d3f8.png)
![image](https://user-images.githubusercontent.com/59267627/120086350-52d29980-c0d6-11eb-991c-a4a106751286.png)

> Upon relaunching nvim

![image](https://user-images.githubusercontent.com/59267627/120086371-667e0000-c0d6-11eb-9758-5c054f67cbfd.png)

> Packer install command

```  
use {
    'AckslD/nvim-revJ.lua',
    requires = {'sgur/vim-textobj-parameter'},
}
```

I have also tried to install `sgur/vim-textobj-parameter` on its own and using vim-plug and the error persists, so I think there is something wrong with that module. I am on neovim v0.5.

**Comment by ram02z** [comment]
Turns out there that `sgur/vim-textobj-parameter` has its own dependancy that was not listed on the README. I have created a pull request regarding the issue.

**Comment by ram02z** [comment]
Also, a side note regarding the plugin's performance (I am using the defaults shown in the README) :
- The only mode that works for is the line one and its very slow and has the wrong indentation despite my shiftwidth equal to 2. See gif below.
![revj_2](https://user-images.githubusercontent.com/59267627/120087293-7e598200-c0de-11eb-924b-4c5252b088cd.gif)

- The operator mode throws an error when I try to use the f motion. I used the t motion and it yanked the whole file.
![image](https://user-images.githubusercontent.com/59267627/120087032-654fd180-c0dc-11eb-987c-8d89b80d727a.png)

- The visual mode I cant seem get to work.

Also, I didn't know of the J command before this, so I might be misusing this plugin.

**Comment by AckslD** [comment]
Thanks for reporting @ram02z!

Regarding your first point this was indeed a bug where the local shiftwidth was not updated, this should be fixed in #16. Btw I'm working on some automated tests which is not fully finished yet but I've added this as a test case. So this solves the indentation issue but I'm not sure why it's to slow for you. What's your `timeoutlen` for example?

Regarding your other points I suspect you're not actually selecting the correct region. Does it work if you put the cursor on the space just after `{` and type `<leader>Jt}`? It is true though that the way faulty regions are handled should probably be improved.

**Comment by ram02z** [comment]
@AckslD I can confirm that the local shiftwidth fix works well. I have tried lowering my timeoutlen from `1000` to `500` and I am not able to notice a discernable difference Here is a demonstration comparing it to more mature plugin, splitjoin.vim:
![revj_3](https://user-images.githubusercontent.com/59267627/120307902-672bb780-c2cb-11eb-83d3-9c9996e8dde6.gif)

> Demo above was with `timeoutlen=500`

I have also tested another plugin vim-argwrap, and I get similar speed to splitjoin.vim when unwrapping a line.
Finally, I was indeed misusing the other two modes, they work well now. I can drop a PR later to describe the usage in more depth for modes like the operator and visual mode, unless you are planning on changing the default behaviour later on.

**Comment by AckslD** [comment]
@ram02z Thanks for reporting! I'll have to look into what might make it slow for you. I'll open a separate issue for this. If possible it would be very helpful if you could [profile](https://neovim.io/doc/user/repeat.html#profile) what actually is slow.

Regarding the documentation of the operator and visual mode any contribution is very welcome. I'm not planning to change their behaviour as of now, apart from better error messages and avoiding half-executed operation if there is an error.
